### ISSUE TITLE
Server error spam, locks server until killed

### ISSUE THREAD

**Issue by RogueRaiden** [TaskaRaine/Ancient-Tools#73] opened 2023-07-12 00:11 UTC
dunno what caused it, 27 players online lol

[https://pastebin.com/gWLXFwFB](https://pastebin.com/gWLXFwFB)

**Comment by TaskaRaine** [comment] 2023-07-15 00:07
Hmm, seems it happened when repairing a cart. But the crash itself happens in vanilla code so I'm not sure exactly what about it would be crashing. I can't seem to quickly reproduce it, either. It very well could be something related to Net7, which I've not looked into at all yet. I will though, when I can.

If you do happen to know a reliable set of steps to reproduce the crash that'd be very helpful

**Comment by Diometus** [comment] 2023-07-23 14:37
Could the override you have going for "OnHeldInteractStep" that is introducing to the client/server as "OnHeldInteractStep_Patch1" be causing the problem by affecting the "OnHeldUseStep" in the API  or "OnUsingTick" within the server in some way? Perhaps missing something to pass off to "OnUsingTtick" when your logic for repairing the cart is being in used? I looked at those 4 and something is going on between them but I cannot quite place what.

"Vintagestory.API.Common.CollectibleObject.OnHeldInteractStep_Patch1"  ---- looked at in your source where "OnHeldInteractStep" is being used followed by the logic you use for repair/damage detection of the cart.

"Vintagestory.API.Common.CollectibleObject.OnHeldInteractStep" ---- in the API itself before the _Patch1 is applied from your source files

I then looked at "Vintagestory.API.Common.CollectibleObject.OnHeldUseStep" within the API followed by "Vintagestory.Server.ServerSystemInventory.OnUsingTick"
ps. got to love ILSpy since no other way to read "Vintagestory.Server."


I really hope you're able to figure it out. Would be interesting to know what it was if you do from an educational standpoint.

**Comment by TaskaRaine** [comment] 2023-07-23 17:36
It's hard to know exactly, unfortunately. I know XSkills/XLib modifies the OnHeldInteractStep function on CollectibleObject. I _believe_ this is why we're seeing the '_Patch1' on the error report. That's where the error is thrown, on the base CollectibleObject function which is being modified by some harmony patch that isn't my own. Unfortunately, since the source for those mods are not publicly available, I can't determine what(if any) part if it may be causing problems. I suppose I could use ILSpy, too.... but I really don't like to do that. It's private for a reason and I'd prefer to not step on peoples toes. The only reason I know that they have a Harmony modification to CollectibleObject is thanks to the FairPlayGuardian mod which has a feature that displays all Harmony patches in an audit file.

Crashes on Harmony-modified code are a challenge because the line number the error reporter prints is generally incorrect. It says the line where the crash occurs is the closing bracket of the function, when looked at via the vanilla source code, which is impossible(as far as I'm aware). 

I tried installing various mods present in the other report RogueRaiden made regarding an issue, including XLib/XSkills, and things seemed to work properly in my test world. That was single player, and not on a .net7 client. Without reproducible steps though... this is difficult to track down. I don't even know XSkills, I've never played with it, so trying to find the right combination of conditions to trigger this crash is daunting. And that's assuming XSkills is even the culprit.

**Comment by Diometus** [comment] 2023-07-24 02:08
I know you could not reproduce it in a single-player world. I just want to inform you in case you were not fully aware, that there are some mods that will work in single-player but not in multiplayer despite using the exact same mods in single-player that are used in multiplayer. One is the Volumetric Shading (Updated) mod that has no problem in a single-player world but when you attempt to go multiplayer with it, it instantly crashes with no way to fix it unless you disable the mod.

I have reported that though to the mod author who has updated the mod based on the original author's code; however, my point in telling you this is to open you up to the possibility that it only occurs on multiplayer servers and not a single-player world; therefore, it may not be able to be reproduced unless you have a multiplayer server you are using in a controlled environment where only you can enter/exit from.  

Just something to think about. :) And I fully understand not wanting to step on other's toes but if it's modifying something in your mod unintentionally, I would think you have the right to go in and try to fix it on your end so it doesn't 'taint' your mod's code boundaries.

**Comment by TaskaRaine** [comment] 2023-08-15 15:16
This issue should now be resolved with the release of Ancient Tools 1.5.8. Please re-open this issue if it still persists, however!

Thanks for the report ^_^

**Closed by TaskaRaine** 2023-08-15 15:16 UTC
Labels: bug, next update
